// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/27/2025, 6:20:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/plugins/**/*.{js,ts,mjs}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/composables/**/*.{js,ts,mjs}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/utils/**/*.{js,ts,mjs}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/OneDrive/Desktop/GoIt/Proiecte Teme de casa/Nuxt3-Tailwind/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;